version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
      - image: mongo:3.4.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm test
          environment:
            MONGODB_URI: 'mongodb://127.0.0.1/votacao_aceleradora'

  deploy:
      machine:
          enabled: true
      working_directory: ~/circleci-demo-workflows
      environment:
        HEROKU_APP: "votacao-aceleradora"
      steps:
        - checkout
        - run:
            name: Setup Heroku
            command: bash .circleci/heroku-setup.sh

        - run:
            command: |
              git push heroku master
              sleep 5
              heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
