version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
      - image: mongo:3.4.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm test
          environment:
            MONGODB_URI: 'mongodb://127.0.0.1/votacao_aceleradora'
